fn part1() -> Result<(), std::io::Error> {
    Ok(())
}

fn part2() -> Result<(), std::io::Error> {
    Ok(())
}

fn main() -> Result<(), std::io::Error> {
    part1()?;
    part2()?;
    Ok(())
}
